/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9yPKYrtYPnCNEj6BTTfHnY

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsnlcKhjNEh2L } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: NlcKhjN_EH2L/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsnlcKhjNEh2L
});
