// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../../components/plasmic/liom_tools/PlasmicGlobalContextsProvider";

import { ThemeContextProvider } from "../../components/plasmic/liom_tools/PlasmicGlobalVariant__Theme";
import { UnnamedGlobalGroupOfVariantsContextProvider } from "../../components/plasmic/liom_tools/PlasmicGlobalVariant__UnnamedGlobalGroupOfVariants";
import { NewViewContextProvider } from "../../components/plasmic/liom_tools/PlasmicGlobalVariant__NewView";
import { PlasmicStepNewwww } from "../../components/plasmic/liom_tools/PlasmicStepNewwww";
import { useRouter } from "next/router";

function StepNewwww() {
  // Use PlasmicStepNewwww to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicStepNewwww are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicStepNewwww is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).

  return (
    <NewViewContextProvider value={undefined}>
      <UnnamedGlobalGroupOfVariantsContextProvider value={undefined}>
        <ThemeContextProvider value={undefined}>
          <GlobalContextsProvider>
            <PageParamsProvider__
              route={useRouter()?.pathname}
              params={useRouter()?.query}
              query={useRouter()?.query}
            >
              <PlasmicStepNewwww />
            </PageParamsProvider__>
          </GlobalContextsProvider>
        </ThemeContextProvider>
      </UnnamedGlobalGroupOfVariantsContextProvider>
    </NewViewContextProvider>
  );
}

export default StepNewwww;
